package logisticsapp.commands.enums;

public enum CommandType {
    CREATELOCATION,
    CREATEROUTE,
    CREATETRUCK,
    CREATECUSTOMER,
    CREATEPACKAGE,

    ASSIGNPACKAGE,
    ASSIGNTRUCK,

    CHANGESTATE,

    SAVEHISTORY,
    LOADHISTORY,

    SHOWCUSTOMERINFO,
    SHOWDELIVERYPACKAGEINFO,
    SHOWTRUCKINFO,
    SHOWROUTEINFO,
    SHOWALLCUSTOMERS,
    SHOWALLDELIVERYPACKAGES,
    SHOWALLTRUCKS,
    SHOWALLROUTES
}